language: node_js
node_js:
   # TODO: Re-enable when Travis CI fixes image dependency problems
   # See: https://github.com/silvermine/standardization/issues/39
   # - "node" # Latest node version
   - "lts/*" # Latest LTS version
   - "14"
   - "12"

cache: false

before_install: npm i -g npm@6.14.12;

script:
   - node --version
   - npm --version
   - npm run standards
   - commitlint-travis
   - grunt clean build
   - npm test

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
